consulta/urls.py
from django.shortcuts import render
from . import views
from django.conf.urls import url

urlpatterns = [
    url('expediente/paciente/', views.home, name="expediente_paciente"),
    url('expediente/edit/(?P<pk>\d+)/$', views.update, name="expediente_update"),
    url('expediente/ref/(?P<pk>\d+)/$', views.find_ref, name="find_ref"),
    url('expediente/save/ref/', views.save_ref, name="save_ref"),
    url('expediente/delete/ref/', views.delete_ref, name="delete_ref"),
    url('expediente/read/ref/', views.get_by_key, name="get_by_key_ref"),
    url('expediente/update/ref/', views.update_ref, name="update_ref"),
    url('expediente/med/(?P<pk>\d+)/$', views.find_med, name="find_med"),
    url('expediente/med/save/', views.save_med, name="save_med"),
    url('expediente/med/delete/', views.delete_med, name="delete_med"),
    url('expediente/med/get_by_key/', views.get_by_key_med, name="get_by_key_med"),
    url('expediente/med/update/', views.update_med, name="update_med"),
    url('expediente/exa/(?P<pk>\d+)/$', views.find_exa, name="find_exa"),
    url('expediente/exa/save/', views.save_exa, name="save_exa"),
    url('expediente/exa/delete/', views.delete_exa, name="delete_exa"),
    url('expediente/exa/get_by_key/', views.get_by_key_exa, name="get_by_key_exa"),
    url('expediente/exa/update/', views.update_exa, name="update_exa"),
]

core/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.home, name='home'),
]

horario/urls.py
from django.shortcuts import render
from . import views
from django.conf.urls import url

urlpatterns = [
    url('horario/consulta/', views.home, name="horario_consulta"),
    url('horario/find/q/', views.find_consulta, name='horario_consulta_query'),
    url('horario/find/today/', views.show_today, name='horario_cons_today'),
    url('horario/save/pac/', views.save_pac_hor, name='horario_save_pac'),
    url('horario/del/pac/', views.delete_horario, name='horario_delete_pac'),
]

myclinic/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.contrib.auth import views
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^login/$', views.LoginView.as_view(), {'template_name': 'registration/login.html'}, name='login'),
    url(r'^logout/$', views.LogoutView.as_view(), {'next_page': '/login'}, name='logout'),
    url('accounts/login/$', views.LoginView.as_view(), {'template_name': 'registration/login.html'}, name='back_logout'),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path(r'', include('core.urls')),
    path(r'', include('horario.urls')),
    path(r'', include('paciente.urls')),
    path(r'', include('consulta.urls')),
    path(r'', include('crud.urls')),
]

consulta/forms.py
from django import forms
from core.models import Consultas, Referencias

class ExpedienteForm(forms.ModelForm):
    class Meta:
        model = Consultas
        fields = ('id', 'id_medico', 'problema', 'diagnostico', 'tratamiento', 'recomendacion', 'talla', 'peso', 'presion_art',)

horario/forms.py
from django import forms

class HorConsultaForm(forms.Form):
    vdate = forms.CharField(max_length=10)

consulta/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
import core.generalFunction as gf
from django.core import serializers
from django.db.models import Max
from core.models import Consultas, Referencias, ConsultasMed, ExamenesDiag
from .forms import ExpedienteForm
import consulta.service as service
import logging
from django.db import connection

log = logging.getLogger(__name__)

@login_required
def home(request):
    try:
        pk = request.GET.get('pk')
        if not pk:
            return render(request, 'expediente.html', {'msg': 'Ha ocurrido un error al tratar de recuperar el expediente del paciente', 'type': 'error'})
        consulta_recover = service.recover_consulta(pk, request.user.username)
        return render(request, 'expediente.html', {'consulta': consulta_recover})
    except Exception as inst:
        log.error(inst)
        return render(request, 'expediente.html', {'msg': 'Ha ocurrido un error inesperado', 'type': 'error'})

@login_required
def update(request, pk):
    try:
        if (request.method == "POST" and request.is_ajax()):
            consulta = get_object_or_404(Consultas, id_medico=gf.findUser(request.user.username), id=pk)
            form = ExpedienteForm(request.POST, instance=consulta)
            if form.is_valid():
                consulta = form.save(commit=False)
                if consulta.id_paciente.fecha_nac:
                    consulta.edad_paciente = service.calculate_age(consulta.id_paciente.fecha_nac)
                if consulta.talla and consulta.peso:
                    consulta.imc = service.calculate_imc(consulta.talla, consulta.peso)
                consulta.save()
            else:
                log.error(form.errors)
                return JsonResponse({'msg': 'Existe un campo que posee un valor incorrecto<br>' + str(form.errors), 'type': 'error'})
            return JsonResponse({'msg': 'Se ha guardado correctamente la consulta', 'type': 'success'})
    except Exception as inst:
        log.error(inst)
        return JsonResponse({'msg': 'Ha ocurrido un error al tratar de guardar la consulta', 'type': 'error'})

@login_required
def find_ref(request, pk):
    try:
        if(request.method == 'POST' and request.is_ajax()):
            data = service.find_ref_query(pk, gf.findUser(request.user.username))
            return JsonResponse({'ref_list': data, 'type': 'success'})
    except Exception as inst:
        log.error(inst)
        return JsonResponse({'msg': 'Ha ocurrido un error al momento de recuperar las referencias m&eacute;dicas', 'type': 'error'})

@login_required
def save_ref(request):
    try:
        esp = request.POST.get('esp')
        med = request.POST.get('med')
        pro = request.POST.get('pro')
        ana = request.POST.get('ana')
        id = request.POST.get('id')
        service.save_ref(esp, med, pro, ana, id, gf.findUser(request.user.username), request.user.username)
        data = service.find_ref_query(id, gf.findUser(request.user.username))
        return JsonResponse({'ref_list': data, 'type': 'success', 'msg': 'Se ha guardado correctamente la referencia'})
    except Exception as inst:
        log.error(inst)
        return JsonResponse({'msg': 'Ha ocurrido un error al momento de guardar la referencia m&eacute;dica', 'type': 'error'})

@login_required
def delete_ref(request):
    try:
        id_ref = request.POST.get('id_ref')
        id_consulta = request.POST.get('id_consulta')
        model = get_object_or_404(Referencias, id = id_ref)
        model.delete()
        data = service.find_ref_query(id_consulta, gf.findUser(request.user.username))
        return JsonResponse({'ref_list': data, 'type': 'success', 'msg': 'Se ha eliminado correctamente la referencia'})
    except Exception as inst:
        log.error(inst)
        return JsonResponse({'type': 'error', 'msg': 'Ha ocurrido un error al tratar de eliminar la referencia'})

@login_required
def get_by_key(request):
    try:
        if(request.method == 'POST' and request.is_ajax()):
            pk = request.POST.get('pk')
            model = get_object_or_404(Referencias, id = pk)
            array_result = serializers.serialize('json', [model], ensure_ascii = False)
            obj = array_result[1:-1]
            return JsonResponse({'ref_single': obj, 'type': 'success'})
    except Exception as inst:
        log.error(inst)
        return JsonResponse({'type': 'error', 'msg': 'Ha ocurrido un error al tratar de recuperar la referencia que desea modificar'})

@login_required
def update_ref(request):
    try:
        if(request.method == 'POST' and request.is_ajax()):
            id_ref = request.POST.get('id_ref')
            model = get_object_or_404(Referencias, id = id_ref)
            model.problema_ref = request.POST.get('pro')
            model.analisis_ref = request.POST.get('ana')
            model.medico_ref = request.POST.get('med')
            model.especialidad_ref = request.POST.get('esp')
            model.save()
            data = service.find_ref_query(model.id_consulta, gf.findUser(request.user.username))
            return JsonResponse({'ref_list': data, 'type':'success', 'msg': 'Se ha actualizado correctamente la referencia'})
    except Exception as inst:
        log.error(inst)
        return JsonResponse({'type': 'error', 'msg': 'Ha ocurrido un error al tratar de actualizar la referencia'})

@login_required
def find_med(request, pk):
    try:
        if(request.method == 'POST' and request.is_ajax()):
            med_list = service.find_med_query(pk, gf.findUser(request.user.username))
            return JsonResponse({'med_list': med_list, 'type': 'success'})
    except Exception as inst:
        log.error(inst)
        return JsonResponse({'type': 'error', 'msg': 'Ha ocurrido un error al tratar de recuperar los medicamentos otorgados'})

@login_required
def save_med(request):
    try:
        if(request.method == 'POST' and request.is_ajax()):
            user = request.user.username
            id_doctor = gf.findUser(user)
            pk = request.POST.get('id_consulta')
            service.save_med(request.POST.get('nom'), request.POST.get('can'), request.POST.get('fus'), id_doctor, user, pk)
            med_list = service.find_med_query(pk, id_doctor)
            return JsonResponse({'med_list': med_list, 'type': 'success', 'msg': 'Se ha guardado correctamente el medicamento'})
    except Exception as inst:
        log.error(inst)
        return JsonResponse({'type': 'error', 'msg': 'Ha ocurrido un error al tratar de guardar un medicamento'})

@login_required
def delete_med(request):
    try:
        if(request.method == 'POST' and request.is_ajax()):
            model = get_object_or_404(ConsultasMed, id = request.POST.get('id_med'))
            pk = model.id_consulta
            model.delete()
            med_list = service.find_med_query(pk, gf.findUser(request.user.username))
            return JsonResponse({'med_list': med_list, 'type': 'success', 'msg': 'Se ha eliminado correctamente el medicamento'})
    except Exception as inst:
        log.error(inst)
        return JsonResponse({'type': 'error', 'msg': 'Ha ocurrido un error al tratar de eliminar el medicamento'})

@login_required
def get_by_key_med(request):
    try:
        if(request.method == 'POST' and request.is_ajax()):
            pk = request.POST.get('pk')
            model = get_object_or_404(ConsultasMed, id = pk)
            array_result = serializers.serialize('json', [model], ensure_ascii = False)
            obj = array_result[1:-1]
            return JsonResponse({'ref_single': obj, 'type': 'success'})
    except Exception as inst:
        log.error(inst)
        return JsonResponse({'type': 'error', 'msg': 'Ha ocurrido un error al tratar de recuperar el medicamento que desea modificar'})

@login_required
def update_med(request):
    try:
        if(request.method == 'POST' and request.is_ajax()):
            model = get_object_or_404(ConsultasMed, id = request.POST.get('id_med'))
            model.nombre_medicamento = request.POST.get('nom')
            model.cantidad = request.POST.get('can')
            model.forma_uso = request.POST.get('fum')
            model.save(force_update=True)
            med_list = service.find_med_query(model.id_consulta, gf.findUser(request.user.username))
            return JsonResponse({'med_list': med_list, 'type': 'success', 'msg': 'Se ha actualizado correctamente el medicamento'})
    except Exception as inst:
        log.error(inst)
        return JsonResponse({'type': 'error', 'msg': 'Ha ocurrido un error al momento de actualizar el medicamento'})

@login_required
def find_exa(request, pk):
    try:
        if(request.method == 'POST' and request.is_ajax()):
            exa_list = service.find_exa_query(pk, gf.findUser(request.user.username))
            return JsonResponse({'exa_list': exa_list, 'type': 'success'})
    except Exception as inst:
        log.error(inst)
        return JsonResponse({'type': 'error', 'msg': 'Ha ocurrido un error al tratar de recuperar los ex&aacute;menes'})

@login_required
def save_exa(request):
    try:
        if(request.method == 'POST' and request.is_ajax()):
            user = request.user.username
            id_doctor = gf.findUser(user)
            pk = request.POST.get('id_consulta')
            service.save_exa(request.POST.get('exa'), id_doctor, user, pk)
            exa_list = service.find_exa_query(pk, id_doctor)
            return JsonResponse({'exa_list': exa_list, 'type': 'success', 'msg': 'Se ha guardado correctamente el ex&aacute;men'})
    except Exception as inst:
        log.error(inst)
        return JsonResponse({'type': 'error', 'msg': 'Ha ocurrido un error al tratar de guardar el ex&aacute;men'})

@login_required
def delete_exa(request):
    try:
        if(request.method == 'POST' and request.is_ajax()):

horario/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from core.models import HorariosOcupados, Paciente, Horarios
from django.http import JsonResponse
import core.generalFunction as gf
from core.models import Usuario
from .forms import HorConsultaForm
from django.core import serializers
import datetime
import logging

log = logging.getLogger(__name__)


@login_required
def home(request):
    try:
        today = gf.getToday()
        today_string = gf.dateToString(today)
        pac_list = Paciente.objects.filter(id_medico = gf.findUser(request.user.username)).order_by('nombre')
        return render(request, 'consulta.html', {'day': today_string, 'pac_list': pac_list})
    except Exception as inst:
        log.error(inst)
        return render(request, 'consulta.html', {'error_msg': 'Ha ocurrido un error al momento de recuperar los pacientes y/o horarios disponibles de este día'})


@login_required
def show_today(request):
    try:
        today = gf.getToday()
        medico = gf.findUser(request.user.username)
        data = get_lists(gf.dateToString(today), medico, '', '')
        return JsonResponse(data, safe=False)
    except Exception as e:
        log.error(e)
        return JsonResponse({'msg': 'Ha ocurrido un error al momento de recuperar los pacientes y/o horarios disponibles de este día', 'type': 'error'}, safe=False)


@login_required
def find_consulta(request):
    try:
        if (request.method == "POST" and request.is_ajax()):
            form = HorConsultaForm(request.POST)
            medico = gf.findUser(request.user.username)
            day = form.data['vdate']
            data = get_lists(day, medico, '', '')
            return JsonResponse(data, safe=False)
    except Exception as inst:
        log.error(inst)
        return JsonResponse({'error_msg': 'Ha ocurrido un error al momento de recuperar los pacientes y/o los horarios disponibles'}, safe=False)


@login_required
def save_pac_hor(request):
    try:
        if (request.method == "POST" and request.is_ajax()):
            id_hor = request.POST.get('id_hor')
            id_pac = request.POST.get('id_pac')
            vdate = request.POST.get('vdate')

            day = datetime.datetime.strptime(vdate, '%d/%m/%Y')
            medico = gf.findUser(request.user.username)

            model = HorariosOcupados()
            model.id_horario = Horarios.objects.get(id = id_hor)
            model.id_paciente = Paciente.objects.get(id = id_pac)
            model.id_medico = medico
            model.fecha = day
            model.usuario_crea = request.user.username
            model.fec_crea = datetime.datetime.now()
            model.efectiva = 'N'
            model.save()

            data = get_lists(vdate, medico, 'Se ha reservado el cupo correctamente', 'success')

            return JsonResponse(data, safe=False)
    except Exception as inst:
        log.error(inst)
        return JsonResponse({'msg': 'Ha ocurrido un error al tratar de reservar el cupo', 'type': 'error'}, safe=False)


@login_required
def delete_horario(request):
    try:
        if (request.method == "POST" and request.is_ajax()):
            id_hor = request.POST.get('id_hor_delete')
            vdate = request.POST.get('vdate')
            model = HorariosOcupados.objects.filter(id = int(id_hor))
            model.delete()
            data = get_lists(vdate, gf.findUser(request.user.username), 'Se ha eliminado correctamente la reserva', 'success')
            return JsonResponse(data, safe=False)   
    except Exception as inst:
        log.error(inst)
        return JsonResponse({'msg': 'Ha ocurrido un error al tratar eliminar la reserva', 'type': 'error'}, safe=False)


def get_lists(vdate, medico, txt_msg, type_msg):
    weekday = gf.stringToWeekday(vdate)
    day_format = gf.toformat_YYYYMMDD(vdate)
    horario_list = HorariosOcupados.objects.filter(id_medico = medico, fecha = day_format).order_by('id_horario')
    dispo_hor_list = Horarios.objects.filter(id_medico = medico, dia = weekday).exclude(id__in = HorariosOcupados.objects.values('id_horario').filter(id_medico = medico, fecha = day_format) ).order_by('inicio')
    data_hor_list = serializers.serialize('json', horario_list, indent=1, use_natural_foreign_keys=True, use_natural_primary_keys=True)
    data_dispo_hor = serializers.serialize('json', dispo_hor_list)
    data = {'horario_list': data_hor_list, 'dispo_hor_list': data_dispo_hor, 'msg': txt_msg, 'type': type_msg}
    return data

horario/templates/consulta.html
{% extends 'base.html' %}
{% block content %}
{% load compress %}
<form method="POST" id="mf" action="{% url 'horario_consulta_query' %}">
    {% csrf_token %}
    <div id="msg" style="color:red"></div>
    <div id="wng"></div>
    {% if error_msg %}
    <div class="alert alert-danger">{{error_msg}}</div>
    {% endif %}
    <div class="row align-items-center">
        <div class="col-md-4 col-sm-12">
            <button type="button" onclick="window.location.href='{% url 'paciente_home' %}'" class="btn-g">Nuevo paciente</button>
        </div>
        <div class="col-md-8" style="text-align: right">
            Fecha de consulta:
            <input type="text" class="fc text-center" id="id_vdate" name="vdate" placeholder="dd/mm/yyyy" value="{{ day }}"
                style="margin-left:5px" />
            <button type="button" id="qb" class="btn-g">Buscar</button>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <h5>Horarios de consulta reservados</h5>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div class="table-responsive">
                <table class="table table-bordered table-hover">
                    <thead>
                        <tr>
                            <th scope="col">Horario</th>
                            <th scope="col">Paciente</th>
                            <th scope="col">Estado</th>
                            <th scope="col"></th>
                        </tr>
                    </thead>
                    <tbody style="background:#fff" id="tb">
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <br /><br />
    <div class="row">
        <div class="col">
            <h5>Horarios disponibles</h5>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div class="table-responsive">
                <table class="table table-bordered table-hover">
                    <thead>
                        <tr>
                            <th scope="col">Horario</th>
                            <th scope="col"></th>
                        </tr>
                    </thead>
                    <tbody style="background:#fff" id="tbd">
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="modal fade" id="mnp" tabindex="-1" role="dialog" aria-labelledby="tp" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <div class="modal-title" id="tp" style="font-weight:bold"></div>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <select id="psl" class="form-control">
                        {% if pac_list %}
                            {% for p in pac_list %}
                                <option value="{{p.id}}">{{p.nombre}}</option>
                            {% endfor %}
                        {% endif %}
                    </select>
                </div>
                <div class="modal-footer">
                    <input type="hidden" id="id_hor"/>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                    <button type="button" class="btn btn-primary" onclick="spo()">Guardar</button>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="mnp" tabindex="-1" role="dialog" aria-labelledby="tp" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <div class="modal-title" id="tp" style="font-weight:bold"></div>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <select id="psl" class="form-control">
                        {% if pac_list %}
                            {% for p in pac_list %}
                                <option value="{{p.id}}">{{p.nombre}}</option>
                            {% endfor %}
                        {% endif %}
                    </select>
                </div>
                <div class="modal-footer">
                    <input type="hidden" id="id_hor"/>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                    <button type="button" class="btn btn-primary" onclick="spo()">Guardar</button>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="del_div" tabindex="-1" role="dialog" aria-labelledby="deltp" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-body" id="del_div_body"></div>
                    <div style="padding-bottom: 10px;padding-right: 15px;text-align: right;">
                        <input type="hidden" id="id_hor_del"/>
                        <button type="button" class="btn btn-primary" onclick="del_hor_ef()" style="margin-right:10px">Si</button>
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
{% endblock %}
{% block javascript %}
{% compress js inline%}
<script>
    function del_hor(id_hor, name, ini, end){
        $('#del_div_body').empty().append('¿Esta seguro que desea eliminar la reserva de ' + name + ' que esta de ' + ini + ' a ' + end + '?');
        $('#del_div').modal();
        $('#id_hor_del').val(id_hor);
    }

    function del_hor_ef(){
        flag = validate();
        if(flag){
            var param = {id_hor_delete : $('#id_hor_del').val(), vdate : $('#id_vdate').val(), csrfmiddlewaretoken: '{{ csrf_token }}'};
            $.ajax({
                type: 'POST',
                url: '{% url 'horario_delete_pac' %}',
                data: param,
                dataType: 'json'
            }).done(function(data){
                display_show_msg(data);
                $('#del_div').modal('hide');
            });
        }
    }

    function display_show_msg(data){
        $('#wng').empty().append(data.msg);
        if(data.type == 'error'){
            $('#wng').addClass('alert alert-danger');
        }else if(data.type == 'warning')
            $('#wng').addClass('alert alert-warning');
        else{
            if(data.msg != null && data.msg != '')
                $('#wng').addClass('alert alert-success');
            data_or_error(data.horario_list);
            data_or_error_disp(data.dispo_hor_list);
        }
    }

    function spo(){
        var id_hor = $('#id_hor').val();
        var id_pac = $('#psl').val();
        var vdate = $('#id_vdate').val();
        flag = validate();
        if(flag){
            $.ajax({
                type: 'POST',
                url: '{% url 'horario_save_pac' %}',
                data:{
                    csrfmiddlewaretoken: '{{ csrf_token }}',
                    id_hor: id_hor,
                    id_pac: id_pac,
                    vdate: vdate    
                },
                dataType: 'json'
            }).done(function(data){
                $('#mnp').modal('hide');
                display_show_msg(data);
            });
        }else
            $('#mnp').modal('hide');
    }
    $(function () {
        $.ajax({
            type: 'POST',
            url: '{% url 'horario_cons_today' %}',
            data: {
                csrfmiddlewaretoken: '{{ csrf_token }}'
            },
            dataType: 'json'
        }).done(function (data) {
            display_show_msg(data);
        });
    });

    function data_or_error(data) {
        if (!$.isEmptyObject(data.error_msg)) {
            $('#wng').addClass('alert alert-danger');
            $('#wng').empty().append(data.error_msg);
        } else
            getTbody(data);
    }

    function data_or_error_disp(data) {
        if (!$.isEmptyObject(data.error_msg)) {
            $('#wng').addClass('alert alert-danger');
            $('#wng').empty().append(data.error_msg);
        } else
            getTbodyDisp(data);
    }

    function sm(id, i, ini, end){
        document.getElementById('mnp').id = 'mnp' + i;
        $('#mnp' + i).modal();
        $('#id_hor').val(id);
        $('#tp').empty().append('Agregar paciente: ' + ini + ' - ' + end);
        document.getElementById('mnp' + i).id = 'mnp';
    }

    function getTbodyDisp(data) {
        row = jQuery.parseJSON(data);
        $('#tbd').empty();
        var tr = ''
        var size = row.length;
        if (size > 0) {
            var ini, end;
            for (i = 0; i < size; i++) {
                ini = String(row[i].fields.inicio).split(',');
                end = String(row[i].fields.fin).split(',');
                tr += '<tr><td>' + ini[0].substring(0, 5) + ' - ' + end[0].substring(0, 5) + '</td><td class="text-center"><a href="javascript:sm(\'' + row[i].pk + '\',\''+i+'\', \'' + ini[0].substring(0, 5) + '\', \'' + end[0].substring(0, 5) + '\')">[Agregar paciente]</a></td></tr>';
            }
        } else
            tr = '<tr><td colspan="2" class="text-center">No hay cupos disponibles</td></tr>';
        $('#tbd').html(tr);
    }

    function getTbody(data) {
        row = jQuery.parseJSON(data);
        $('#tb').empty();
        var tr = '';
        var size = row.length;
        if (size > 0) {
            var t, state;
            for (i = 0; i < size; i++) {
                t = String(row[i].fields.id_horario).split(',');
                if(row[i].fields.efectiva == 'N')
                    state = '<font style="color:#e8ae00;font-weight:bold">Pendiente</font>';
                else if(row[i].fields.efectiva == 'S')
                    state = '<font style="color:green;font-weight:bold">Efectuada</font>';
                tr += '<tr><td>' + t[0].substring(0, 5) + ' - ' + t[1].substring(0, 5) + '</td><td>' + row[i].fields.id_paciente + '</td><td>' + state + '</td><td class="text-center"><a href="{% url "expediente_paciente" %}?pk=' + row[i].pk + '">[Ir a consulta]</a> - <a href="javascript:del_hor(\'' + row[i].pk + '\', \'' + row[i].fields.id_paciente + '\', \'' + t[0].substring(0, 5) + '\', \'' + t[1].substring(0, 5) + '\')">[Eliminar]</a></td></tr>';
            }
        } else
            tr = '<tr><td colspan="4" class="text-center">No hay citas para este d&iacute;a</td></tr>';
        $('#tb').html(tr);
    }

    $(document).ready(function () {
        $('#qb').click(function (event) {
            flag = validate();
            if (flag) {
                $.ajax({
                    type: 'POST',
                    url: '{% url 'horario_consulta_query' %}',
                    data: $('#mf').serialize(),
                    dataType: 'json'
                }).done(function (data) {
                    display_show_msg(data);
                });
            }
        });
    });

    function validate() {
        $('#wng').empty().removeClass('alert alert-warning');
        var d = $('#id_vdate').val();
        if (d == '') {
            $('#wng').addClass('alert alert-warning');
            $('#wng').empty().append('El campo fecha esta vacio, debe ingresar una fecha valida (formato DD/MM/YYYY)');
            return false;
        }
        if (isDate(d))
            return true;
        else {
            $('#wng').addClass('alert alert-warning');
            $('#wng').empty().append('El formato de la fecha es incorrecto, debe ser DD/MM/YYYY');
            return false;
        }
        return true;
    }

</script>
{% endcompress %}
{% endblock %}