consulta/urls.py
from django.shortcuts import render
from . import views
from django.conf.urls import url

urlpatterns = [
    url('expediente/paciente/', views.home, name="expediente_paciente"),
    url('expediente/edit/(?P<pk>\d+)/$', views.update, name="expediente_update"),
    url('expediente/ref/(?P<pk>\d+)/$', views.find_ref, name="find_ref"),
    url('expediente/save/ref/', views.save_ref, name="save_ref"),
    url('expediente/delete/ref/', views.delete_ref, name="delete_ref"),
    url('expediente/read/ref/', views.get_by_key, name="get_by_key_ref"),
    url('expediente/update/ref/', views.update_ref, name="update_ref"),
    url('expediente/med/(?P<pk>\d+)/$', views.find_med, name="find_med"),
    url('expediente/med/save/', views.save_med, name="save_med"),
    url('expediente/med/delete/', views.delete_med, name="delete_med"),
    url('expediente/med/get_by_key/', views.get_by_key_med, name="get_by_key_med"),
    url('expediente/med/update/', views.update_med, name="update_med"),
    url('expediente/exa/(?P<pk>\d+)/$', views.find_exa, name="find_exa"),
    url('expediente/exa/save/', views.save_exa, name="save_exa"),
    url('expediente/exa/delete/', views.delete_exa, name="delete_exa"),
    url('expediente/exa/get_by_key/', views.get_by_key_exa, name="get_by_key_exa"),
    url('expediente/exa/update/', views.update_exa, name="update_exa"),
]

core/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.home, name='home'),
]

myclinic/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.contrib.auth import views
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^login/$', views.LoginView.as_view(), {'template_name': 'registration/login.html'}, name='login'),
    url(r'^logout/$', views.LogoutView.as_view(), {'next_page': '/login'}, name='logout'),
    url('accounts/login/$', views.LoginView.as_view(), {'template_name': 'registration/login.html'}, name='back_logout'),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path(r'', include('core.urls')),
    path(r'', include('horario.urls')),
    path(r'', include('paciente.urls')),
    path(r'', include('consulta.urls')),
    path(r'', include('crud.urls')),
]

core/models.py
from django.db import models

class EspecialidadesMedicas(models.Model):
    nombre = models.CharField(max_length=300, blank=True, null=True)
    usuario_crea = models.CharField(max_length=15, blank=True, null=True)
    fec_crea = models.DateTimeField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'especialidades_medicas'

        
class Roles(models.Model):
    nombre = models.CharField(max_length=50, blank=True, null=True)
    descripcion = models.CharField(max_length=1000, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'roles'


class Usuario(models.Model):
    id = models.CharField(primary_key=True, max_length=15)
    pwd = models.CharField(max_length=1000)
    nombre = models.CharField(max_length=2000, blank=True, null=True)
    correo = models.CharField(max_length=40, blank=True, null=True)
    clinica = models.CharField(max_length=2000, blank=True, null=True)
    fec_creacion = models.DateTimeField(blank=True, null=True)
    id_rol = models.ForeignKey(Roles, models.DO_NOTHING, db_column='id_rol', blank=True, null=True)
    estado = models.CharField(max_length=5, blank=True, null=True)
    usuario_crea = models.CharField(max_length=15, blank=True, null=True)
    id_usuario = models.ForeignKey('self', models.DO_NOTHING, db_column='id_usuario', blank=True, null=True)
    fecha_cancelado = models.DateTimeField(blank=True, null=True)
    logo = models.CharField(max_length=45, blank=True, null=True)
    sexo = models.CharField(max_length=1, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'usuario'


class MedicoEspecialidad(models.Model):
    id_especialidad = models.ForeignKey(EspecialidadesMedicas, models.DO_NOTHING, db_column='id_especialidad', primary_key=True)
    id_usuario = models.ForeignKey('Usuario', models.DO_NOTHING, db_column='id_usuario')
    usuario_crea = models.CharField(max_length=15, blank=True, null=True)
    fec_crea = models.DateTimeField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'medico_especialidad'
        unique_together = (('id_especialidad', 'id_usuario'),)

class PacienteManager(models.Manager):
    def get_by_natural_key(nombre):
        return self.get(nombre=nombre)

class Paciente(models.Model):
    objects = PacienteManager()

    nombre = models.CharField(max_length=3000, blank=True, null=True)
    fecha_nac = models.DateField(blank=True, null=True)
    sexo = models.CharField(max_length=1, blank=True, null=True)
    correo = models.CharField(max_length=30, blank=True, null=True)
    celular = models.CharField(max_length=15, blank=True, null=True)
    telefono_casa = models.CharField(max_length=15, blank=True, null=True)
    telefono_oficina = models.CharField(max_length=15, blank=True, null=True)
    aseguradora = models.CharField(max_length=100, blank=True, null=True)
    id_medico = models.ForeignKey('Usuario', models.DO_NOTHING, db_column='id_medico', blank=True, null=True)
    usuario_crea = models.CharField(max_length=15, blank=True, null=True)
    fec_crea = models.DateTimeField(blank=True, null=True)
    dui = models.CharField(max_length=11, blank=True, null=True)
    direccion = models.CharField(max_length=4000, blank=True, null=True)
    estado_civil = models.CharField(max_length=1, blank=True, null=True)
    profesion = models.CharField(max_length=4000, blank=True, null=True)
    empresa = models.CharField(max_length=2000, blank=True, null=True)
    direccion_empresa = models.CharField(max_length=4000, blank=True, null=True)
    municipio = models.CharField(max_length=3, blank=True, null=True)

    def natural_key(self):
        return (self.nombre)

    class Meta:
        managed = False
        db_table = 'paciente'


class AuditoriaInout(models.Model):
    usuario = models.CharField(max_length=15, blank=True, null=True)
    fecha = models.DateTimeField(blank=True, null=True)
    accion = models.CharField(max_length=2, blank=True, null=True)
    mes = models.IntegerField(blank=True, null=True)
    year = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'auditoria_inout'


class AuthGroup(models.Model):
    name = models.CharField(unique=True, max_length=80)

    class Meta:
        managed = False
        db_table = 'auth_group'


class AuthGroupPermissions(models.Model):
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)
    permission = models.ForeignKey('AuthPermission', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_group_permissions'
        unique_together = (('group', 'permission'),)


class AuthPermission(models.Model):
    name = models.CharField(max_length=255)
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING)
    codename = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'auth_permission'
        unique_together = (('content_type', 'codename'),)


class AuthUser(models.Model):
    password = models.CharField(max_length=128)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.BooleanField
    username = models.CharField(unique=True, max_length=150)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=150)
    email = models.CharField(max_length=254)
    is_staff = models.SmallIntegerField()
    is_active = models.SmallIntegerField()
    date_joined = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'auth_user'


class AuthUserGroups(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_groups'
        unique_together = (('user', 'group'),)


class AuthUserUserPermissions(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    permission = models.ForeignKey(AuthPermission, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_user_permissions'
        unique_together = (('user', 'permission'),)


class Consultas(models.Model):
    id_medico = models.ForeignKey('Usuario', models.DO_NOTHING, db_column='id_medico')
    #id = models.IntegerField()
    id_horario = models.ForeignKey('HorariosOcupados', models.DO_NOTHING, db_column='id_horario')
    id_paciente = models.ForeignKey('Paciente', models.DO_NOTHING, db_column='id_paciente')
    fecha = models.DateField()
    problema = models.CharField(max_length=5000, blank=True, null=True)
    tratamiento = models.CharField(max_length=5000, blank=True, null=True)
    recomendacion = models.CharField(max_length=5000, blank=True, null=True)
    talla = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    peso = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    presion_art = models.CharField(max_length=20, blank=True, null=True)
    imc = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    usuario_crea = models.CharField(max_length=15, blank=True, null=True)
    fec_crea = models.DateTimeField(blank=True, null=True)
    observacion_receta = models.CharField(max_length=4000, blank=True, null=True)
    edad_paciente = models.IntegerField(blank=True, null=True)
    diagnostico = models.CharField(max_length=5000, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'consultas'
        unique_together = (('id_medico', 'id'),)


class ConsultasMed(models.Model):
    id_medico = models.ForeignKey('Usuario', models.DO_NOTHING, db_column='id_medico')
    id_consulta = models.IntegerField()
    nombre_medicamento = models.CharField(max_length=3000, blank=True, null=True)
    cantidad = models.CharField(max_length=200, blank=True, null=True)
    forma_uso = models.CharField(max_length=3000, blank=True, null=True)
    usuario_crea = models.CharField(max_length=15, blank=True, null=True)
    fec_crea = models.DateTimeField(blank=True, null=True)
    casa = models.CharField(max_length=2000, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'consultas_med'
        #unique_together = (('id_medico', 'id_consulta'),)

class DjangoAdminLog(models.Model):
    action_time = models.DateTimeField()
    object_id = models.TextField(blank=True, null=True)
    object_repr = models.CharField(max_length=200)
    action_flag = models.SmallIntegerField()
    change_message = models.TextField()
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING, blank=True, null=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'django_admin_log'


class DjangoContentType(models.Model):
    app_label = models.CharField(max_length=100)
    model = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'django_content_type'
        unique_together = (('app_label', 'model'),)


class DjangoMigrations(models.Model):
    app = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    applied = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_migrations'


class DjangoSession(models.Model):
    session_key = models.CharField(primary_key=True, max_length=40)
    session_data = models.TextField()
    expire_date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_session'


class ExamenesDiag(models.Model):
    id_medico = models.ForeignKey('Usuario', models.DO_NOTHING, db_column='id_medico')
    id_consulta = models.IntegerField()
    usuario_crea = models.CharField(max_length=15, blank=True, null=True)
    fec_crea = models.DateTimeField(blank=True, null=True)
    resultado = models.CharField(max_length=4000, blank=True, null=True)

consulta/forms.py
from django import forms
from core.models import Consultas, Referencias

class ExpedienteForm(forms.ModelForm):
    class Meta:
        model = Consultas
        fields = ('id', 'id_medico', 'problema', 'diagnostico', 'tratamiento', 'recomendacion', 'talla', 'peso', 'presion_art',)

consulta/templates/datos_generales.html
<div class="row" style="margin-bottom:18px">
    <div class="col">
        <label for="talla">Talla:</label>
        <input type="text" class="form-control" id="id_talla" name="talla" autofocus placeholder="En metros"/>
    </div>
    <div class="col">
        <label for="peso">Peso:</label>
        <input type="text" class="form-control" id="id_peso" name="peso" placeholder="En libras"/>
    </div>
    <div class="col">
        <label for="presion_art">Presi&oacute;n arterial:</label>
        <input type="text" class="form-control" id="id_presion_art" name="presion_art"/>
    </div>
</div>
<div class="form-group">
    <label for="problema">Definici&oacute;n de problema *:</label>
    <textarea id="id_problema" class="form-control" placeholder="Escriba la raz&oacute;n de la consulta" name="problema"></textarea>
</div>
<div class="form-group">
    <label for="diagnostico">Diagn&oacute;stico del paciente *:</label>
    <textarea id="id_diagnostico" class="form-control" placeholder="Escriba el/los diagn&oacute;stico(s) del paciente" name="diagnostico"></textarea>
</div>
<div class="form-group">
    <label for="tratamiento">Tratamiento recomendado *:</label>
    <textarea id="id_tratamiento" class="form-control" placeholder="Escriba los tratamientos recomendados" name="tratamiento"></textarea>
</div>
<div class="form-group">
    <label for="recomendacion">Recomendaciones:</label>
    <textarea id="id_recomendacion" class="form-control" placeholder="Escriba las recomendaciones que sugiere en base a la consulta" name="recomendacion"></textarea>
</div>
<div class="form-group">
    <button type="button" class="btn-g" id="upd_btn" onclick="save_form()">Guardar</button>
</div>

consulta/templates/examenes.html
<div class="form-group" style="margin-bottom:18px">
    <label for="examen">Nombre del ex&aacute;men *:</label>
    <input type="text" id="examen" class="form-control" placeholder="Escriba el nombre del ex&aacute;men" name="examen"/>
</div>
<div class="form-group">
    <button type="button" class="btn-g" id="med_btn" onclick="exa_save()">Guardar</button>
</div>
<div class="form-group">
    <div class="table-responsive">
        <table class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th scope="col">Ex&aacute;men</th>
                    <th scope="col">Acci&oacute;n</th>
                </tr>
                <tbody style="background:#fff" id="tb_exa">
                </tbody>
            </thead>
        </table>
    </div>
</div>
<div class="modal fade" id="del_exa_div" tabindex="-1" role="dialog" aria-labelledby="del_exa_tp" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-body" id="del_div_exa_body"></div>
            <div style="padding-bottom: 10px;padding-right: 15px;text-align: right;">
                <input type="hidden" id="id_exa_del"/>
                <button type="button" class="btn btn-primary" onclick="del_exa_svr()" style="margin-right:10px">Si</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="updt_exa_div" tabindex="-1" role="dialog" aria-labelledby="up_exa_tp" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Actualizaci&oacute;n de ex&aacute;men</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label for="examen_updt">Nombre del ex&aacute;men *:</label>
                        <input type="text" id="examen_updt" class="form-control" name="examen_updt"/>
                    </div>
                    <div class="form-group">
                        <input type="hidden" id="id_exa_updt"/>
                        <button type="button" class="btn-g" onclick="update_exa()">Actualizar</button>
                    </div>
                    <div class="form-group">
                        <div id="msg_update_exa"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>

consulta/templates/medicamentos.html
<div class="form-group" style="margin-bottom:18px">
    <label for="nombre_medicamento">Nombre del medicamento *:</label>
    <input type="text" id="nombre_medicamento" class="form-control" placeholder="Escriba el nombre del medicamento" name="nombre_medicamento"/>
</div>
<div class="row">
    <div class="col-6">
        <label for="cantidad">Cantidad *:</label>
        <input type="text" class="form-control" id="cantidad" name="cantidad" placeholder="Cantidad de medicamento otorgado"/>
    </div>
    <div class="col-6">
        <label for="forma_uso">Forma de uso *:</label>
        <input type="text" class="form-control" id="forma_uso" name="forma_uso" placeholder="Defina la forma de uso"/>
    </div>
</div>
<div class="form-group">
    <button type="button" class="btn-g" id="med_btn" onclick="med_save()">Guardar</button>
</div>
<div class="form-group">
    <div class="table-responsive">
        <table class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th scope="col">Medicamento</th>
                    <th scope="col">Cantidad</th>
                    <th scope="col">Forma de uso</th>
                    <th scope="col">Acci&oacute;n</th>
                </tr>
                <tbody style="background:#fff" id="tb_med">
                </tbody>
            </thead>
        </table>
    </div>
</div>
<div class="modal fade" id="del_med_div" tabindex="-1" role="dialog" aria-labelledby="del_med_tp" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-body" id="del_div_med_body"></div>
            <div style="padding-bottom: 10px;padding-right: 15px;text-align: right;">
                <input type="hidden" id="id_med_del"/>
                <button type="button" class="btn btn-primary" onclick="del_med_svr()" style="margin-right:10px">Si</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="updt_med_div" tabindex="-1" role="dialog" aria-labelledby="up_med_tp" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Actualizaci&oacute;n de medicamentos</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <label for="nombre_medicamento">Nombre del medicamento *:</label>
                    <input type="text" id="nombre_medicamento_updt" class="form-control" name="nombre_medicamento_updt"/>
                </div>
                <div class="row">
                    <div class="col-6">
                        <label for="cantidad">Cantidad *:</label>
                        <input type="text" class="form-control" id="cantidad_updt" name="cantidad_updt"/>
                    </div>
                    <div class="col-6">
                        <label for="forma_uso">Forma de uso *:</label>
                        <input type="text" class="form-control" id="forma_uso_updt" name="forma_uso_updt"/>
                    </div>
                </div>
                <div class="form-group">
                    <input type="hidden" id="id_med_updt"/>
                    <button type="button" class="btn-g" id="med_updt_btn" onclick="update_med()">Actualizar</button>
                </div>
                <div class="form-group">
                    <div id="msg_update_med"></div>
                </div>
            </div>
        </div>
    </div>
</div>

consulta/templates/referencias.html
<div class="row" style="margin-bottom:18px">
    <div class="col-6">
        <label for="especialidad_ref">Especialidad *:</label>
        <input type="text" class="form-control" id="id_especialidad_ref" name="especialidad_ref" placeholder="Especialidad del m&eacute;dico"/>
    </div>
    <div class="col-6">
        <label for="medico_ref">Nombre del m&eacute;dico *:</label>
        <input type="text" class="form-control" id="id_medico_ref" name="medico_ref" placeholder="Nombre del m&eacute;dico"/>
    </div>
</div>
<div class="form-group">
    <label for="problema_ref">Definici&oacute;n de problema *:</label>
    <textarea id="id_problema_ref" class="form-control" placeholder="Escriba los diagn&oacute;sticos por los cuales genera la referencia" name="problema_ref"></textarea>
</div>
<div class="form-group">
    <label for="analisis_ref">An&aacute;lisis o raz&oacute;n por la que se hace la referencia *:</label>
    <textarea id="id_analisis_ref" class="form-control" placeholder="An&aacute;lisis de la referencia" name="analisis_ref"></textarea>
</div>
<div class="form-group">
    <button type="button" class="btn-g" id="ref_btn" onclick="save_ref()">Guardar</button>
</div>
<div class="form-group">
    <div class="table-responsive">
        <table class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th scope="col">M&eacute;dico</th>
                    <th scope="col">Problema</th>
                    <th scope="col">An&aacute;lisis</th>
                    <th scope="col">Acci&oacute;n</th>
                </tr>
                <tbody style="background:#fff" id="tb_ref">
                </tbody>
            </thead>
        </table>
    </div>
</div>
<div class="modal fade" id="del_ref_div" tabindex="-1" role="dialog" aria-labelledby="deltp" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-body" id="del_div_ref_body"></div>
            <div style="padding-bottom: 10px;padding-right: 15px;text-align: right;">
                <input type="hidden" id="id_ref_del"/>
                <button type="button" class="btn btn-primary" onclick="del_ref_svr()" style="margin-right:10px">Si</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="updt_ref_div" tabindex="-1" role="dialog" aria-labelledby="up_ref_tp" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Actualizaci&oacute;n de referencia m&eacute;dica</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <label for="problema_ref">Especialidad m&eacute;dica *:</label>
                    <textarea id="id_especialidad_ref_updt" class="form-control" name="id_especialidad_ref_updt"></textarea>
                </div>
                <div class="form-group">
                    <label for="problema_ref">Nombre del m&eacute;dico *:</label>
                    <textarea id="id_medico_ref_updt" class="form-control" name="id_medico_updt"></textarea>
                </div>
                <div class="form-group">
                    <label for="problema_ref">Definici&oacute;n de problema *:</label>
                    <textarea id="id_problema_ref_updt" class="form-control" name="problema_ref_updt"></textarea>
                </div>
                <div class="form-group">
                    <label for="analisis_ref">An&aacute;lisis o raz&oacute;n por la que se hace la referencia *:</label>
                    <textarea id="id_analisis_ref_updt" class="form-control" name="analisis_ref_updt"></textarea>
                </div>
                <div class="form-group">
                    <input type="hidden" name="id_ref_updt" id="id_ref_updt"/>
                    <button type="button" class="btn btn-primary" id="ref_btn" onclick="update_ref()">Actualizar</button>
                </div>
                <div class="form-group">
                    <div id="msg_update_ref"></div>
                </div>
            </div>
        </div>
    </div>
</div>