core/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.home, name='home'),
]

myclinic/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.contrib.auth import views
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^login/$', views.LoginView.as_view(), {'template_name': 'registration/login.html'}, name='login'),
    url(r'^logout/$', views.LogoutView.as_view(), {'next_page': '/login'}, name='logout'),
    url('accounts/login/$', views.LoginView.as_view(), {'template_name': 'registration/login.html'}, name='back_logout'),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path(r'', include('core.urls')),
    path(r'', include('horario.urls')),
    path(r'', include('paciente.urls')),
    path(r'', include('consulta.urls')),
    path(r'', include('crud.urls')),
]

paciente/urls.py
from django.shortcuts import render
from . import views
from django.conf.urls import url

urlpatterns = [
    url('paciente/nuevo/', views.paciente_home, name="paciente_home"),
    url('paciente/find/key', views.find_paciente_by_key, name="paciente_find_by_key"),
    url('paciente/save', views.save_paciente, name="paciente_save"),
    url('paciente/find/', views.find_pacientes, name="paciente_find"),
    url('paciente/all', views.find_pacientes_all, name="paciente_find_all"),
    url('paciente/get/single', views.get_paciente_by_key, name="get_paciente_by_key"),
]

core/models.py
from django.db import models

class EspecialidadesMedicas(models.Model):
    nombre = models.CharField(max_length=300, blank=True, null=True)
    usuario_crea = models.CharField(max_length=15, blank=True, null=True)
    fec_crea = models.DateTimeField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'especialidades_medicas'

        
class Roles(models.Model):
    nombre = models.CharField(max_length=50, blank=True, null=True)
    descripcion = models.CharField(max_length=1000, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'roles'


class Usuario(models.Model):
    id = models.CharField(primary_key=True, max_length=15)
    pwd = models.CharField(max_length=1000)
    nombre = models.CharField(max_length=2000, blank=True, null=True)
    correo = models.CharField(max_length=40, blank=True, null=True)
    clinica = models.CharField(max_length=2000, blank=True, null=True)
    fec_creacion = models.DateTimeField(blank=True, null=True)
    id_rol = models.ForeignKey(Roles, models.DO_NOTHING, db_column='id_rol', blank=True, null=True)
    estado = models.CharField(max_length=5, blank=True, null=True)
    usuario_crea = models.CharField(max_length=15, blank=True, null=True)
    id_usuario = models.ForeignKey('self', models.DO_NOTHING, db_column='id_usuario', blank=True, null=True)
    fecha_cancelado = models.DateTimeField(blank=True, null=True)
    logo = models.CharField(max_length=45, blank=True, null=True)
    sexo = models.CharField(max_length=1, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'usuario'


class MedicoEspecialidad(models.Model):
    id_especialidad = models.ForeignKey(EspecialidadesMedicas, models.DO_NOTHING, db_column='id_especialidad', primary_key=True)
    id_usuario = models.ForeignKey('Usuario', models.DO_NOTHING, db_column='id_usuario')
    usuario_crea = models.CharField(max_length=15, blank=True, null=True)
    fec_crea = models.DateTimeField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'medico_especialidad'
        unique_together = (('id_especialidad', 'id_usuario'),)

class PacienteManager(models.Manager):
    def get_by_natural_key(nombre):
        return self.get(nombre=nombre)

class Paciente(models.Model):
    objects = PacienteManager()

    nombre = models.CharField(max_length=3000, blank=True, null=True)
    fecha_nac = models.DateField(blank=True, null=True)
    sexo = models.CharField(max_length=1, blank=True, null=True)
    correo = models.CharField(max_length=30, blank=True, null=True)
    celular = models.CharField(max_length=15, blank=True, null=True)
    telefono_casa = models.CharField(max_length=15, blank=True, null=True)
    telefono_oficina = models.CharField(max_length=15, blank=True, null=True)
    aseguradora = models.CharField(max_length=100, blank=True, null=True)
    id_medico = models.ForeignKey('Usuario', models.DO_NOTHING, db_column='id_medico', blank=True, null=True)
    usuario_crea = models.CharField(max_length=15, blank=True, null=True)
    fec_crea = models.DateTimeField(blank=True, null=True)
    dui = models.CharField(max_length=11, blank=True, null=True)
    direccion = models.CharField(max_length=4000, blank=True, null=True)
    estado_civil = models.CharField(max_length=1, blank=True, null=True)
    profesion = models.CharField(max_length=4000, blank=True, null=True)
    empresa = models.CharField(max_length=2000, blank=True, null=True)
    direccion_empresa = models.CharField(max_length=4000, blank=True, null=True)
    municipio = models.CharField(max_length=3, blank=True, null=True)

    def natural_key(self):
        return (self.nombre)

    class Meta:
        managed = False
        db_table = 'paciente'


class AuditoriaInout(models.Model):
    usuario = models.CharField(max_length=15, blank=True, null=True)
    fecha = models.DateTimeField(blank=True, null=True)
    accion = models.CharField(max_length=2, blank=True, null=True)
    mes = models.IntegerField(blank=True, null=True)
    year = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'auditoria_inout'


class AuthGroup(models.Model):
    name = models.CharField(unique=True, max_length=80)

    class Meta:
        managed = False
        db_table = 'auth_group'


class AuthGroupPermissions(models.Model):
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)
    permission = models.ForeignKey('AuthPermission', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_group_permissions'
        unique_together = (('group', 'permission'),)


class AuthPermission(models.Model):
    name = models.CharField(max_length=255)
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING)
    codename = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'auth_permission'
        unique_together = (('content_type', 'codename'),)


class AuthUser(models.Model):
    password = models.CharField(max_length=128)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.BooleanField
    username = models.CharField(unique=True, max_length=150)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=150)
    email = models.CharField(max_length=254)
    is_staff = models.SmallIntegerField()
    is_active = models.SmallIntegerField()
    date_joined = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'auth_user'


class AuthUserGroups(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_groups'
        unique_together = (('user', 'group'),)


class AuthUserUserPermissions(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    permission = models.ForeignKey(AuthPermission, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_user_permissions'
        unique_together = (('user', 'permission'),)


class Consultas(models.Model):
    id_medico = models.ForeignKey('Usuario', models.DO_NOTHING, db_column='id_medico')
    #id = models.IntegerField()
    id_horario = models.ForeignKey('HorariosOcupados', models.DO_NOTHING, db_column='id_horario')
    id_paciente = models.ForeignKey('Paciente', models.DO_NOTHING, db_column='id_paciente')
    fecha = models.DateField()
    problema = models.CharField(max_length=5000, blank=True, null=True)
    tratamiento = models.CharField(max_length=5000, blank=True, null=True)
    recomendacion = models.CharField(max_length=5000, blank=True, null=True)
    talla = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    peso = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    presion_art = models.CharField(max_length=20, blank=True, null=True)
    imc = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    usuario_crea = models.CharField(max_length=15, blank=True, null=True)
    fec_crea = models.DateTimeField(blank=True, null=True)
    observacion_receta = models.CharField(max_length=4000, blank=True, null=True)
    edad_paciente = models.IntegerField(blank=True, null=True)
    diagnostico = models.CharField(max_length=5000, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'consultas'
        unique_together = (('id_medico', 'id'),)


class ConsultasMed(models.Model):
    id_medico = models.ForeignKey('Usuario', models.DO_NOTHING, db_column='id_medico')
    id_consulta = models.IntegerField()
    nombre_medicamento = models.CharField(max_length=3000, blank=True, null=True)
    cantidad = models.CharField(max_length=200, blank=True, null=True)
    forma_uso = models.CharField(max_length=3000, blank=True, null=True)
    usuario_crea = models.CharField(max_length=15, blank=True, null=True)
    fec_crea = models.DateTimeField(blank=True, null=True)
    casa = models.CharField(max_length=2000, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'consultas_med'
        #unique_together = (('id_medico', 'id_consulta'),)

class DjangoAdminLog(models.Model):
    action_time = models.DateTimeField()
    object_id = models.TextField(blank=True, null=True)
    object_repr = models.CharField(max_length=200)
    action_flag = models.SmallIntegerField()
    change_message = models.TextField()
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING, blank=True, null=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'django_admin_log'


class DjangoContentType(models.Model):
    app_label = models.CharField(max_length=100)
    model = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'django_content_type'
        unique_together = (('app_label', 'model'),)


class DjangoMigrations(models.Model):
    app = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    applied = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_migrations'


class DjangoSession(models.Model):
    session_key = models.CharField(primary_key=True, max_length=40)
    session_data = models.TextField()
    expire_date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_session'


class ExamenesDiag(models.Model):
    id_medico = models.ForeignKey('Usuario', models.DO_NOTHING, db_column='id_medico')
    id_consulta = models.IntegerField()
    usuario_crea = models.CharField(max_length=15, blank=True, null=True)
    fec_crea = models.DateTimeField(blank=True, null=True)
    resultado = models.CharField(max_length=4000, blank=True, null=True)

paciente/forms.py
from django.forms import ModelForm
from core.models import Paciente
from django import forms

class PacienteForm(ModelForm):
    class Meta:
        model = Paciente
        fields = ['nombre', 'sexo', 'correo', 'celular', 'telefono_casa', 'telefono_oficina', 'aseguradora', 'dui', 'direccion', 'estado_civil', 'profesion', 'empresa', 'direccion_empresa', 'municipio']
        

paciente/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from core.models import Paciente
from .forms import PacienteForm
import core.generalFunction as gf
from django.core import serializers
import logging
from django.utils import timezone

log = logging.getLogger(__name__)

@login_required
def paciente_home(request):
    try:
        pac_list = Paciente.objects.filter(id_medico = gf.findUser(request.user.username)).order_by('nombre')
        return render(request, 'paciente.html', {'pac_list': pac_list})
    except Exception as inst:
        log.error(inst)
        return render(request, 'paciente.html')

@login_required
def find_paciente_by_key(request):
    try:
        if (request.method == "POST" and request.is_ajax()):
            id_pac = request.POST.get('name_pac')
            paciente_list = Paciente.objects.filter(nombre = id_pac, id_medico = gf.findUser(request.user.username))
            data = serializers.serialize('json', paciente_list)
            return JsonResponse({"paciente": data}, safe=False)
    except Exception as inst:
        log.error(inst)
        return JsonResponse({'msg': 'Ha ocurrido un error al recuperar el paciente que selecciono', 'type': 'error'}, safe=False)

@login_required
def save_paciente(request):
    try:
        if (request.method == "POST" and request.is_ajax()):
            user = request.user.username
            model = PacienteForm(request.POST)
            paciente = model.save(commit = False)
            fecha_nac = request.POST.get('fecha_nac')
            paciente.id_medico = gf.findUser(user)
            paciente.fecha_nac = gf.toformat_YYYYMMDD(fecha_nac)
            paciente.usuario_crea = user
            paciente.fec_crea = timezone.now()
            paciente.save()
            return JsonResponse({'msg': 'Se ha guardado correctamente el paciente', 'type': 'success'}, safe=False)
    except Exception as inst:
        log.error(inst)
        return JsonResponse({'msg': 'Ha ocurrido un error al tratar de guardar el paciente', 'type': 'error'}, safe=False)

@login_required
def find_pacientes(request):
        return render(request, 'paciente_consulta.html')


@login_required
def find_pacientes_all(request):
        try:
                pac_list = Paciente.objects.filter(id_medico = gf.findUser(request.user.username)).order_by('nombre')
                data = serializers.serialize('json', pac_list)
                return JsonResponse({'pac_list': data})
        except Exception as inst:
                log.error(inst)
                return JsonResponse({'msg': 'Ha ocurrido un error inesperado al recuperar los pacientes', 'type': 'error'})

@login_required
def get_paciente_by_key(request):
        try:
                if (request.method == 'POST' and request.is_ajax()):
                        id_pac = request.POST.get('id_pac')
                        paciente = get_object_or_404(Paciente, pk=id_pac)
                        array_result = serializers.serialize('json', [paciente], ensure_ascii = False)
                        obj = array_result[1:-1]
                        return JsonResponse({'paciente': obj, 'type': 'success'})
                else:
                        return JsonResponse({'msg': 'Ha ocurrido un error al tratar de acceder a la informaci&oacute;n del paciente', 'type': 'error'})
        except Exception as inst:
                log.error(inst)
                return JsonResponse({'msg': 'Ha ocurrido un error al tratar de recuperar la informaci&oacute;n del paciente', 'type': 'error'})

paciente/templates/paciente.html
{% extends 'base.html' %}
{% block content %}
{% load compress %}
<div class="row">
	<div class="col titl_w">
		Ingreso de nuevo paciente
	</div>
</div>
<div class="row">
	<div class="col">
		<h5>1) Verificar si el paciente ya existe</h5>
	</div>
</div>
<div class="row">
	<div class="col">
        <input id="pc" name="pc" list="list_pac" oninput="show_pac()" class="form-control" autofocus="autofocus" placeholder="Ingrese el nombre del paciente para verificar si ya esta registrado"/>
        <datalist id="list_pac">
            {% for paciente in pac_list%}
                <option value="{{paciente.nombre}}"/>
            {% endfor %}
        </datalist>
	</div>
</div>
<div style="height:50px"></div>
<div class="row">
	<div class="col">
		<h5>2) En el caso que no exista, ingrese el nuevo paciente</h5>
	</div>
</div>
<form method="POST" id="mf">
	<div class="row">
		<div class="col">
			<div id="msg_form"></div>
		</div>
	</div>
	{% csrf_token %}
	<div class="row">
		<div class="col">
			<label for="id_nombre">Nombre del paciente *:</label>
			<input type="text" name="nombre" id="id_nombre" class="form-control" placeholder="Nombre">
		</div>
		<div class="col">
			<label for="id_fecha_nac">Fecha de nacimiento *:</label>
			<input type="text" name="fecha_nac" id="id_fecha_nac" class="form-control" placeholder="dd/mm/yyyy"/>
		</div>
		<div class="col">
			<label for="id_sexo">Sexo:</label>
			<select name="sexo" id="id_sexo" class="form-control">
				<option value="M">Mujer</option>
				<option value="H">Hombre</option>
			</select>
		</div>
	</div>
	<div class="row">
		<div class="col">
			<label for="id_municipio">Departamento:</label>
			<select name="municipio" id="id_municipio" class="form-control">
				<option value="AHC">Ahuachap&aacute;n</option>
				<option value="CAB">Caba&ntilde;as</option>
				<option value="CHA">Chalatenango</option>
				<option value="CUS">Cuscatl&aacute;n</option>
				<option value="LIB">La Libertad</option>
				<option value="PAZ">La Paz</option>
				<option value="UNI">La Uni&oacute;n</option>
				<option value="MOR">Moraz&aacute;n</option>
				<option value="SMI">San Miguel</option>
				<option value="SSA">San Salvador</option>
				<option value="SVI">San Vicente</option>
				<option value="SAN">Santa Ana</option>
				<option value="SON">Sonsonate</option>
				<option value="USU">Usulut&aacute;n</option>
			</select>
		</div>
		<div class="col">
			<label for="id_direccion">Direcci&oacute;n:</label>
			<input type="text" name="direccion" id="id_direccion" class="form-control" placeholder="Direcci&oacute;n del paciente"/>
		</div>
		<div class="col">
			<label for="id_estado_civil">Estado civil:</label>
			<select name="estado_civil" id="id_estado_civil" class="form-control">
				<option value="S">Soltero/a</option>
				<option value="O">Comprometido/a</option>
				<option value="C">Casado/a</option>
				<option value="D">Divorciado/a</option>
				<option value="V">Viudo/a</option>
			</select>
		</div>
	</div>
	<div class="row">
		<div class="col">
			<label for="id_telefono_casa">Telefono casa:</label>
			<input type="text" name="telefono_casa" id="id_telefono_casa" class="form-control" placeholder="Tel. casa" maxlength="8"/>
		</div>
		<div class="col">
			<label for="id_telefono_oficina">Telefono oficina:</label>
			<input type="text" name="telefono_oficina" id="id_telefono_oficina" class="form-control" placeholder="Tel. ofic." maxlength="8"/>
		</div>
		<div class="col">
			<label for="id_celular">Celular *:</label>
			<input type="text" name="celular" id="id_celular" class="form-control" placeholder="Celular" maxlength="8"/>
		</div>
	</div>
	<div class="row">
		<div class="col">
			<label for="id_correo">Correo *:</label>
			<input type="text" id="id_correo" name="correo" class="form-control" placeholder="Correo"/>
		</div>
		<div class="col">
			<label for="id_aseguradora">Aseguradora:</label>
			<input type="text" id="id_aseguradora" name="aseguradora" class="form-control" placeholder="Aseguradora"/>
		</div>
		<div class="col">
			<label for="id_dui">DUI (con gui&oacute;n):</label>
			<input type="text" name="dui" id="id_dui" class="form-control" placeholder="DUI" maxlength="10"/>
		</div>
	</div>
	<div class="row">
		<div class="col">
			<label for="id_profesion">Profesi&oacute;n:</label>
			<input type="text" name="profesion" id="id_profesion" class="form-control" placeholder="Profesi&oacute;n"/>
		</div>
		<div class="col">
			<label for="id_empresa">Empresa:</label>
			<input type="text" name="empresa" id="id_empresa" class="form-control" placeholder="Empresa"/>
		</div>
		<div class="col">
			<label for="id_direccion_empresa">Direcci&oacute;n de Empresa:</label>
			<input type="text" name="direccion_empresa" id="id_direccion_empresa" class="form-control" placeholder="Direcci&oacute;n de la empresa"/>
		</div>
	</div>
	<div class="row">
			<div class="col">
				* son campos obligatorios
			</div>
		</div>
	<div class="row">
		<div class="col">
			<button type="button" class="btn-g" id="btnSave" onclick="save_form()">Guardar paciente</button>
		</div>
	</div>
</form>
<div class="modal fade" id="mdp" tabindex="-1" role="dialog" aria-labelledby="tp" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<div class="modal-title" id="tp" style="font-weight:bold"></div>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				<div id="modal_content"></div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-primary" data-dismiss="modal">Cerrar</button>
			</div>
		</div>
	</div>
</div>
{% endblock %}
{% block javascript %}
{% compress js inline%}
<script>
    function show_pac(){
        var val = document.getElementById('pc').value;
        var opts = document.getElementById('list_pac').childNodes;
        for (var i = 0; i < opts.length; i++) {
          if (opts[i].value === val) {
			param = {csrfmiddlewaretoken:'{{ csrf_token }}', name_pac:opts[i].value};
			$.ajax({
                type: 'POST',
                url: '{% url 'paciente_find_by_key' %}',
                data: param,
                dataType: 'json'
            }).done(function (data){
				if (!$.isEmptyObject(data.msg)) {
					$('#msg_form').addClass('alert alert-danger');
					$('#msg_form').empty().append(data.msg);
				}else{
					pac = jQuery.parseJSON(data.paciente);
					if(pac.length > 1){
						alert('Existe mas de un paciente con el mismo nombre, sera correcto eso? se mostrará la información del primer paciente');
					}
					$('#tp').empty().append('Paciente: ' + pac[0].fields.nombre);
					var html = '<table class="table"><tr><td>DUI:</td><td>' + nvl(pac[0].fields.dui, '') + '</td></tr>';
					html += '<tr><td>Correo:</td><td>' + nvl(pac[0].fields.correo, '') + '</td></tr>';
					html += '<tr><td>Celuar:</td><td>' + nvl(pac[0].fields.celular, '') + '</td></tr>';
					date = '';
					if(pac[0].fields.fecha_nac != '' && pac[0].fields.fecha_nac != null){
						dates = pac[0].fields.fecha_nac.split('-');
						date = dates[2] + '/' + dates[1] + '/' + dates[0];
					}
					html += '<tr><td>Fecha de nac.:</td><td>' + date + '</td></tr>';
					$('#modal_content').empty().append(html);
					$('#mdp').modal();
				}
            });
            break;
          }
        }
	}
	
	function save_form(){
		inputs = ['id_nombre', 'id_fecha_nac', 'id_celular', 'id_correo'];
		reset_validate_form(inputs);
		var nombre = $('#id_nombre').val();
		var fecnac = $('#id_fecha_nac').val();
		var celular = $('#id_celular').val();
		var correo = $('#id_correo').val();
		flag = true;
		if(nombre == ''){
			val_input_danger('Debe ingresar el nombre del paciente', 'id_nombre');
			flag = false;
		}if(fecnac == ''){
			val_input_danger('Debe ingresar la fecha de nacimiento del paciente', 'id_fecha_nac');
			flag = false;
		}else if(isDate(fecnac) == false){
			val_input_danger('La fecha de nacimiento debe poseer el formato DD/MM/YYYY', 'id_fecha_nac');
			flag = false;
		}if(celular == ''){
			val_input_danger('Debe ingresar el celular del paciente', 'id_celular');
			flag = false;
		}if(correo == ''){
			val_input_danger('Debe ingresar el correo del paciente', 'id_correo');			
			flag = false;
		}
		if(flag){
			$.ajax({
				type: 'POST',
				url: '{% url 'paciente_save' %}',
				data: $('#mf').serialize(),
				dataType: 'json'
			}).done(function (data){
				if(data.type == 'success'){
					$('#msg_form').addClass('alert alert-success');
				}else if(data.type == 'error')
					$('#msg_form').addClass('alert alert-danger');
				$('#msg_form').empty().append(data.msg);
			});
		}
	}
</script>
{% endcompress %}
{% endblock %}